### PR TITLE
Grammatical corrections in learn.md

### PR DESCRIPTION
**Pull request by alwindoss**
More Grammatical corrections.

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
Great, thanks a lot!

**Comment by alwindoss** [comment]
I would love to help. I am an experienced Java Developer and I a new to Scala would love to contribute so thought best place to start is documentation

**Comment by OlegIlyenko** [comment]
Yeah, definitely, I would really appreciate any help and PRs. Also if you have interesting ideas how to improve scaldi library itself or anything that surrounds it, like website, docs, etc., then I would like to encourage you to share it here on github, or mailing list. 

I wanted to write some docs about the internals of the library, so that it is easier for people to contribute (several people asked me to do this already), but I haven't managed to do it yet. Hope soon I will get an opportunity to sit down and do it properly :)

**Comment by alwindoss** [comment]
Sure I could help you with it. I am totally new to Scaldi, let me get myself familiar with it too.

**Pull request merged**
