### PR TITLE
Changed a typo in the main page

### PR DESCRIPTION
**Pull request by alwindoss**
Will contribute more in my free time.

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
thanks a lot!

**Comment by alwindoss** [comment]
@OlegIlyenko is there a way I can contact you. Throught twitter or email?

**Comment by OlegIlyenko** [comment]
sure, https://twitter.com/easyangel we can also exchange emails in DMs as well :)

**Comment by alwindoss** [comment]
I follow you now and I a https://twitter.com/alwindoss
If you follow me we could DM Each other

**Pull request merged**
